name: time_price
description: Переводит стоимость покупок в рабочее время.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+3
  path: ^1.9.0
  home_widget: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#0C0C11" # цвет фона твоей иконки
